FROM golang:latest AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o backend ./cmd/backend

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/backend .
EXPOSE 9001
CMD ["./backend"]